name: Schedule download news Worker
on:
  #push:
  schedule:
    - cron: '10 22,4,10 * * *' #每日6：10,12：10,18:10，三个时间点执行任务，注意时区
jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v4
      - name: 'Download files'
        run: bash ./download.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
