name: Schedule download news Worker
on:
  #push:
  schedule:
    - cron: '10 22,0,2,4,6,8,10,12,14 * * *' #每日6：10~22:10，每隔2小时执行一次任务，注意时区
jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v4
      - name: 'Download files'
        run: bash ./download.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
